### ISSUE TITLE
Password length does not match counter value when checkboxes are toggled

### ISSUE THREAD

**Issue by cjstyles6** [cjstyles6/Password-Generator#1]
The password generator allows the user to specify the password length using a counter that can be incremented and decremented. However, there is a bug where toggling any of the checkboxes for character types (e.g. uppercase, lowercase, numbers, symbols) causes the password length to double, ignoring the counter value.

Expected behavior:
The password length should always match the counter value, regardless of which checkboxes are toggled. Toggling checkboxes should only affect which character types are included.

Possible cause:
The password generation logic is currently duplicating the characters when checkboxes are toggled on. This needs to be updated to respect the counter value rather than double the length.

**Comment by Strange-Quark-007** [comment]
Hello @cjstyles6 

I'll guide you on this - you should be able to fix it on your own

generatePassword is looping from `i = 0` to `counter`
then in getRandom function
if suppose first 3 options are checked, 
then for each `i` it will add 3 such characters
hence the password length that comes at the end is `number of options selected` x `counter`

Instead of simply `return characters.join("");` 
1st randomly select one of the option from user selected options
then run switch case on it to add that specific character

```
const getRandom = () => {
    let characters = [];
    
    if (isUpperCase) { 
      characters.push(
        upperCaseLetters[Math.floor(Math.random() * upperCaseLetters.length)],
      );
    }

    if (isLowerCase) {
      characters.push(
        lowerCaseLetters[Math.floor(Math.random() * lowerCaseLetters.length)],
      );
    }

    if (isNumbers) {
      characters.push(numbers[Math.floor(Math.random() * numbers.length)]);
    }

    if (isSymbols) {
      characters.push(symbols[Math.floor(Math.random() * symbols.length)]);
    }

    return characters.join("");
  };
  ```
  
![image](https://github.com/cjstyles6/Password-Generator/assets/110275359/45844273-8384-46ad-ae44-72ba0d348dfe)


i did setup in local - 
and there is a clear patten based on selected options
uppercase,lowercase,number, and it repeats based on counter/length 


Give a try to work this out on your own

**Comment by cjstyles6** [comment]
Thanks,sounds a little bit confusing but I'll try
